# Generated by Django 5.2.6 on 2025-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='events', to='event.category'),
        ),
    ]
