# Generated by Django 5.2.6 on 2025-10-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_ticket_current_price_ticket_discount_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
