# Generated by Django 5.2.6 on 2025-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_ticketscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cashback_given',
            field=models.BooleanField(default=False),
        ),
    ]
