# Generated by Django 5.2.6 on 2025-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_orderitem_cashback_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cashback_given',
        ),
        migrations.DeleteModel(
            name='TicketScan',
        ),
    ]
