# Generated by Django 5.2.6 on 2025-10-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
