# Generated by Django 5.2.6 on 2025-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=255),
        ),
    ]
