# Generated by Django 5.2.6 on 2025-10-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='customer', max_length=16),
        ),
    ]
